const PRODUCTS = [
  { id: 'p1', name: 'Royal Dinner Set (72 pc)', price: 12199,
    desc: 'Ceramic, dishwasher-safe, premium gloss finish.',
    img: 'itemno1.jpeg' },
  { id: 'p2', name: 'Stainless Steel Cutlery Set (16 pc)', price: 1299,
    desc: 'Mirror-polished, rust-free, modern handle design.',
    img: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80' },
  { id: 'p3', name: 'Dinner Set (72 pcs)', price: 12299,
    desc: 'Lead-free crystal, perfect for elegant dining.',
    img: 'itemno2.jpeg' },
  { id: 'p5', name: 'Tray Set (3 pcs)', price: 2999,
    desc: 'Heavy-base cut-glass cigarette ashtray, elegant for table or lounge.',
    img: 'itemno3.jpeg' },
  { id: 'p6', name: 'Water Bottle', price: 199,
    desc: 'BPA-free, leak-proof, insulated — keeps drinks cool for hours.',
    img: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=800&q=80' },
  { id: 'p7', name: 'Jugs and Glasses', price: 599,
    desc: 'Food-grade steel insert, airtight seal, spill-resistant.',
    img: 'itemno4.jpeg' },
  { id: 'p8', name: 'Tray Set', price: 1199,
    desc: 'Food-grade steel insert, airtight seal, spill-resistant.',
    img: 'pic1.jpeg' },
  { id: 'p9', name: 'Cutlery Set', price: 2499,
    desc: 'Golden color spoons and forks.',
    img: 'pic2.jpeg' },
  { id: 'p10', name: 'Dinner Set with Flower Design (72 pcs)', price: 7999,
    desc: 'Flower design plates.',
    img: 'pic3.jpeg' },
  { id: 'p11', name: 'Dinner Set with Flower Design (72 pcs)', price: 14999,
    desc: 'Double glazed Dinner set with unique material.',
    img: 'pic4.jpeg' },
  { id: 'p12', name: 'Golden Serving Tray', price: 1149,
    desc: 'Golden color gleam serving tray.',
    img: 'pic5.jpeg' },
  { id: 'p13', name: 'Safari Water Bottles', price: 299,
    desc: 'Safari flipper bottle.',
    img: 'pic6.jpeg' },
  { id: 'p14', name: 'Salt and Pepper Set (2 piece)', price: 399,
    desc: 'Salt and pepper set.',
    img: 'pic7.jpeg' },
  { id: 'p15', name: 'Royal Dinner Set (72 pcs)', price: 9999,
    desc: 'Classic premium dinner set.',
    img: 'pic8.jpeg' },
  { id: 'p16', name: 'Iconic Dinner Set (76 pcs)', price: 8999,
    desc: 'Large iconic dinner set for family gatherings.',
    img: 'pic10.jpeg' },
  { id: 'p17', name: 'Royal Melamine Dinner Set (72 pcs)', price: 11499,
    desc: 'Durable melamine dinner set.',
    img: 'pic11.jpeg' },
  { id: 'p18', name: 'Premium Glasses Set (6 pcs)', price: 499,
    desc: 'Glasses set with good quality.',
    img: 'pic12.jpeg' },
  { id: 'p19', name: '04 Size Spoons', price: 1499,
    desc: 'Cutlery set with 04 size spoons.',
    img: 'pic13.jpeg' },
  { id: 'p22', name: 'Flower Design Dinner Set (76 pcs)', price: 11999,
    desc: 'Highly malleable dinner set.',
    img: 'pic16.jpeg' },
  { id: 'p23', name: 'Sipper', price: 1599,
    desc: 'Stanley with red and white color in metal quality.',
    img: 'sipper.jpeg' },
  { id: 'p26', name: 'Jugs', price: 1499,
    desc: 'Black berries jug with flower design (1 pc).',
    img: 'jugs.jpeg' },
  { id: 'p27', name: 'Glass', price: 649,
    desc: 'High-quality water drinking glasses (1 pc).',
    img: 'styleglass.jpeg' },
  { id: 'p28', name: 'Dinner Set (72 pcs)', price: 12499,
    desc: 'High-quality complete dining set.', 
    img: 'dinner1set.jpeg' },
  { id: 'p29', name: 'High Quality Vacuum Flask Jug Set', price: 799,
    desc: 'Thermos for teas and water with simple blue flower design (1 pc).',
    img: 'vaccumflaskjug.jpeg' },
  { id: 'p30', name: 'Vacuum Bottles', price: 999,
    desc: 'Vacuum water bottles for school (1 pc).',
    img: 'vaccumbottle.jpeg' },
  { id: 'p31', name: 'Salt and Pepper Set', price: 799,
    desc: 'Salt and pepper set with brown and white color (6 pcs set).',
    img: 'saltandpeper.jpeg' },
  { id: 'p32', name: 'Glass Set', price: 2299,
    desc: 'Delisoga glassware in white color (6 pcs set).',
    img: 'Thermos.jpeg' },
  { id: 'p33', name: 'Tray Set', price: 2999,
    desc: 'Tray set with wooden material in flower design (3 pcs set).',
    img: 'trayset.jpeg' },
  { id: 'p34', name: 'Plastic Jug', price: 4999,
    desc: 'Golden color jug with 2L capacity (jug and 6 glasses).',
    img: 'plasticjug.jpeg' },
  { id: 'p35', name: 'Ice Cream Set', price: 1199,
    desc: 'White color ice cream bowl set (6 pcs).',
    img: 'icecreamset.jpeg' },
  { id: 'p36', name: 'Plastic Box', price: 399,
    desc: 'Blue color plastic box (1 pc).',
    img: 'plasticbox.jpeg' },
  { id: 'p36b', name: 'Juice Blender', price: 1999,
    desc: 'Juice blender with metal quality.',
    img: '55.jpeg' },
  { id: 'p37', name: 'Plastic Party Jug', price: 499,
    desc: 'Party jug with plastic material in blue color.',
    img: '88.jpeg' },
  { id: 'p38', name: 'Mug', price: 499,
    desc: 'Mug for drinking water in pink color cup with glass plate and glass material.',
    img: 'cup.jpeg' },
  { id: 'p39', name: 'Sipper', price: 1299,
    desc: 'Pink color sipper for girls.',
    img: 'sipper4.jpeg' },
  { id: 'p40', name: 'Vegetable Cutter', price: 599,
    desc: 'Vegetable cutter with good quality blade.',
    img: 'cutter4.jpeg' }
];

window.PRODUCTS = PRODUCTS;

